In [1]:
import pandas as pd

In [2]:
ex = pd.read_csv("DATA_FOR_regression_USDINR_11_state_forecast_1.csv").iloc[:,1:]

In [3]:
ex.iloc[100]

index                              812
DATE                        2017-08-28
TIME                          11:00:00
OPEN                            63.905
HIGH                           63.9225
                               ...
Daily_volatility_wos_min      0.000896
R_S_Volatility_max             0.00234
Daily_volatility_max          0.001529
R_S_Volatility_wos_max        0.002395
Daily_volatility_wos_max      0.001494
Name: 100, Length: 70, dtype: object

In [4]:
ex[100:105]

,index,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOLUME,OI,pre_OPEN,...,Forecasted_wos_HIGH,Forecasted_wos_LOW,R_S_Volatility_min,Daily_volatility_min,R_S_Volatility_wos_min,Daily_volatility_wos_min,R_S_Volatility_max,Daily_volatility_max,R_S_Volatility_wos_max,Daily_volatility_wos_max
100,812,2017-08-28,11:00:00,63.9050,63.9225,63.845,63.9050,547264,792888,64.0525,...,64.040633,63.837796,0.001774,0.000899,0.001729,0.000896,0.002340,0.001529,0.002395,0.001494
101,813,2017-08-29,11:00:00,63.9575,64.2375,63.955,64.2050,618118,1560307,63.9350,...,64.087767,63.872205,0.001892,0.000900,0.001729,0.000896,0.002297,0.001390,0.002395,0.001493
102,814,2017-08-30,11:00:00,64.1425,64.2000,64.065,64.2000,637929,1553005,63.8800,...,64.183638,64.062813,0.001831,0.001036,0.001727,0.000896,0.002448,0.001432,0.002393,0.001488
103,815,2017-08-31,11:00:00,64.1875,64.2000,64.060,64.0775,502820,1533074,64.1250,...,64.241876,64.121877,0.001917,0.000909,0.001725,0.000896,0.002410,0.001500,0.002393,0.001488
104,816,2017-09-01,11:00:00,64.1325,64.2100,64.100,64.1875,575938,1598164,64.1900,...,64.217277,64.079337,0.001827,0.000945,0.001723,0.000896,0.002380,0.001516,0.002391,0.001488

In [5]:
# ex = ex.set_index(["DATE", "TIME"]) # Multiindex data frame - more than one column as index

In [6]:
ex.set_index("DATE", inplace = True)

In [7]:
ex.loc["2023-09-14"]

index                           2273
TIME                        11:00:00
OPEN                           82.99
HIGH                         83.0875
LOW                          82.9875
                              ...
Daily_volatility_wos_min    0.000621
R_S_Volatility_max          0.002463
Daily_volatility_max         0.00141
R_S_Volatility_wos_max      0.002453
Daily_volatility_wos_max    0.001307
Name: 2023-09-14, Length: 69, dtype: object

In [8]:
ex.reset_index(inplace=True) # resets all indexes and makes the index a column again. Inplace = True means it will change the original data frame

In [9]:
ex

,DATE,index,TIME,OPEN,HIGH,LOW,CLOSE,VOLUME,OI,pre_OPEN,...,Forecasted_wos_HIGH,Forecasted_wos_LOW,R_S_Volatility_min,Daily_volatility_min,R_S_Volatility_wos_min,Daily_volatility_wos_min,R_S_Volatility_max,Daily_volatility_max,R_S_Volatility_wos_max,Daily_volatility_wos_max
0,2017-03-29,712,11:00:00,64.9275,65.1925,64.9225,65.1200,773299,1676862,65.3400,...,65.144467,64.818527,0.001744,0.000810,0.001777,0.000896,0.002793,0.001752,0.002514,0.001533
1,2017-03-30,713,11:00:00,65.1425,65.1525,65.0750,65.0975,481041,1671913,65.0925,...,65.228610,65.048410,0.001884,0.000863,0.001777,0.000896,0.002635,0.001507,0.002513,0.001533
2,2017-03-31,714,11:00:00,65.0000,65.1575,64.9900,65.0525,624702,1719557,65.0800,...,65.058417,64.909456,0.001858,0.000766,0.001777,0.000896,0.002497,0.001422,0.002509,0.001533
3,2017-04-03,715,11:00:00,65.0425,65.2700,65.0225,65.2100,659060,1779924,65.0350,...,65.124910,64.961820,0.001886,0.001054,0.001777,0.000896,0.002636,0.001646,0.002508,0.001533
4,2017-04-05,716,11:00:00,65.2450,65.2525,65.0700,65.0750,754094,1676349,64.9600,...,65.318058,65.158016,0.001888,0.001056,0.001777,0.000896,0.002609,0.001628,0.002507,0.001532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,2023-09-11,2270,11:00:00,82.8975,83.1150,82.8850,83.0925,1613114,3882349,83.1900,...,83.032190,82.804717,0.001707,0.000637,0.001424,0.000621,0.002522,0.001389,0.002459,0.001307
1559,2023-09-12,2271,11:00:00,83.0275,83.0550,82.9200,82.9950,1309341,3822793,83.0500,...,83.127616,82.942772,0.001414,0.000570,0.001424,0.000621,0.002556,0.001441,0.002455,0.001307
1560,2023-09-13,2272,11:00:00,82.9700,83.0350,82.9650,83.0175,875942,3822742,82.9900,...,83.032982,82.891835,0.001380,0.000625,0.001424,0.000621,0.002451,0.001148,0.002453,0.001307
1561,2023-09-14,2273,11:00:00,82.9900,83.0875,82.9875,83.0500,874097,3713940,82.9700,...,83.069805,82.927558,0.001498,0.000633,0.001424,0.000621,0.002463,0.001410,0.002453,0.001307
1562,2023-09-15,2274,11:00:00,83.1025,83.2275,83.0175,83.1950,1697834,3615916,83.0150,...,83.183616,83.040094,0.001405,0.000494,0.001424,0.000621,0.002335,0.001214,0.002452,0.001305

In [10]:
# HW:
# Q1: Write a program to find the fibbonacci series.
# Q2: Write a program to find the prime numbers between 25 to 105
# Q3: Write a program to calculate the bmi (body mass index) of a person having height of 167 cm and weight of 30 lb
# also distinguish the bmi index with the defined standards. (formula on google)
# Ranges:
# BMI <17.0: thinness
# BMI <18.5: underweight
# BMI 18.5-24.9: normal weight
# BMI â‰¥25.0: overweight
# BMI â‰¥30.0: obesity.
# Q4: Write a program to find the factorial of 5,6, and 7.
# Q5: Write a program to find the number of combinations that can be formed with 5 players in a batting order
# without using built-in functions.

In [11]:
#Q1:

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return (fibonacci(n-1) + fibonacci(n-2))
    
n = 20
for x in range(n):
    print(fibonacci(x), end = ' ~ ')

0 ~ 1 ~ 1 ~ 2 ~ 3 ~ 5 ~ 8 ~ 13 ~ 21 ~ 34 ~ 55 ~ 89 ~ 144 ~ 233 ~ 377 ~ 610 ~ 987 ~ 1597 ~ 2584 ~ 4181 ~

In [2]:
#Q2:

n1 = 25
n2 = 105

for x in range(n1, n2+1):
    if x > 1:
        for i in range(2, x):
            if x%i == 0:
                break
        else:
            print(x)

29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103

In [13]:
#Q3: 

def bmi(w, h):
    a = (w*0.453592) #lb to kg
    b = h/100
    return a / (b**2)

h = 167 #cm
w = 30 #lb

print("BMI:", bmi(w,h))
if bmi(w,h) < 17:
    print("Thinness")
elif bmi(w,h) < 18.5:
    print("Underwheight")
elif bmi(w,h) > 18.5 and bmi(w,h) < 24.9:
    print("Normal")
elif bmi(w,h) >= 25:
    print("Overwheight")
elif bmi(w,h) >= 30:
    print("Obesity")

BMI: 4.879257054752769
Thinness

In [14]:
#Q4:

def factorial(x):
    if x == 0 or x == 1:
        return 1
    else:
        return x*factorial(x-1)
    
print(factorial(5))
print(factorial(6))
print(factorial(7))

120
720
5040

In [15]:
# Q5: 

def comb(n, r):
    if r<=n:
        return factorial(n)/factorial(n-r)*factorial(r)
print(comb(3, 2))

12.0